<wsdl:definitions
     name="STU_INFO_DBPOLLING"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JUNE2022SOAApplication/CalculateStuGrade/STU_INFO_DBPOLLING"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/JUNE2022SOAApplication/CalculateStuGrade/STU_INFO_DBPOLLING"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/STU_INFO_DBPOLLING"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="STU_INFO_DBPOLLING_plt" >
    <plt:role name="STU_INFO_DBPOLLING_role" >
      <plt:portType name="tns:STU_INFO_DBPOLLING_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/STU_INFO_DBPOLLING" schemaLocation="../Schemas/STU_INFO_DBPOLLING_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="StuInfoCollection_msg">
        <wsdl:part name="StuInfoCollection" element="top:StuInfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="STU_INFO_DBPOLLING_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:StuInfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
