<wsdl:definitions
     name="STU_GRADE_INSERT"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JUNE2022SOAApplication/CalculateStuGrade/STU_GRADE_INSERT"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/JUNE2022SOAApplication/CalculateStuGrade/STU_GRADE_INSERT"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/STU_GRADE_INSERT"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="STU_GRADE_INSERT_plt" >
    <plt:role name="STU_GRADE_INSERT_role" >
      <plt:portType name="tns:STU_GRADE_INSERT_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/STU_GRADE_INSERT" schemaLocation="../Schemas/STU_GRADE_INSERT_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="StuResultCollection_msg">
        <wsdl:part name="StuResultCollection" element="top:StuResultCollection"/>
    </wsdl:message>
    <wsdl:portType name="STU_GRADE_INSERT_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:StuResultCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
