<wsdl:definitions
     name="DB_Insert_Stu_Info"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JUNE2022SOAApplication/PracticeAdapters/DB_Insert_Stu_Info"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/JUNE2022SOAApplication/PracticeAdapters/DB_Insert_Stu_Info"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_Stu_Info"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Insert_Stu_Info_plt" >
    <plt:role name="DB_Insert_Stu_Info_role" >
      <plt:portType name="tns:DB_Insert_Stu_Info_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Insert_Stu_Info" schemaLocation="../Schemas/DB_Insert_Stu_Info_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="StuInfoCollection_msg">
        <wsdl:part name="StuInfoCollection" element="top:StuInfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Insert_Stu_Info_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:StuInfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
