<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://practice.com/JUNE2022SOAApplication/BillingSystem/BillingSystemBPEL" xmlns:ns0="http://pratice.com/JUNE2022SOAApplication/OrderProcessSystem/OPSBPEL" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OPSBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="orderRequest" namespace="http://pratice.com/JUNE2022SOAApplication/OrderProcessSystem/OPSBPEL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/JUNE2022SOAApplication/BillingSystem/WSDLs/BillingSystemBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="bsRequest" namespace="http://practice.com/JUNE2022SOAApplication/BillingSystem/BillingSystemBPEL"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE AUG 02 07:42:32 IST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:bsRequest>
         <tns:orderID>
            <xsl:value-of select="/ns0:orderRequest/ns0:orderID"/>
         </tns:orderID>
         <xsl:for-each select="/ns0:orderRequest/ns0:lineItem">
            <tns:itemInfo>
               <tns:itemName>
                  <xsl:value-of select="ns0:productName"/>
               </tns:itemName>
               <tns:itemCost>
                  <xsl:value-of select="ns0:productCost"/>
               </tns:itemCost>
            </tns:itemInfo>
         </xsl:for-each>
      </tns:bsRequest>
   </xsl:template>
</xsl:stylesheet>
