<wsdl:definitions
     name="StuResult_JMSConsumer"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/JUNE2022SOAApplication/JMSConsumerProject/StuResult_JMSConsumer"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/JUNE2022SOAApplication/JMSConsumerProject/StuResult_JMSConsumer"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:imp1="http://practice.com/file/write/File_Write_stuResult"
    >
  <plt:partnerLinkType name="Consume_Message_plt" >
    <plt:role name="Consume_Message_role" >
      <plt:portType name="tns:Consume_Message_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://practice.com/file/write/File_Write_stuResult" schemaLocation="../Schemas/FileAdapter_StuResult.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Consume_Message_msg">
        <wsdl:part name="body" element="imp1:sturesultCollection"/>
    </wsdl:message>
    <wsdl:portType name="Consume_Message_ptt">
        <wsdl:operation name="Consume_Message">
            <wsdl:input message="tns:Consume_Message_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
